# Blacklist model

## What countries with similar behavior shall we avoid?

### 1 Data cleaning

In [1]:
#importing libraries

import pandas as pd
import numpy as np

In [2]:
#import first csv file

fishdf=pd.read_csv("../data_wrangling/fishvessel_clean.csv")

In [3]:
#import second csv file

illegaldf=pd.read_csv("../data_wrangling/ts_clean.csv")

In [4]:
#check first file

fishdf.head()

mmsi flag gear_type     length     tonnage  engine_power country  \
0  603100157  AGO  trawlers  32.808468  299.003814    733.826977  Angola   
1  603100137  AGO  trawlers  34.568782  395.683171    864.960188  Angola   
2  603100161  AGO  trawlers  28.822140  263.849149    651.809642  Angola   
3  603100174  AGO  trawlers  30.721429  299.700916    703.796086  Angola   
4  603100164  AGO  trawlers  37.479248  405.967747    850.976640  Angola   

   IUU Fishing  
0         2.37  
1         2.37  
2         2.37  
3         2.37  
4         2.37

In [5]:
#check second first

illegaldf.head()

fishing_vessel_mmsi  transshipment_vessel_mmsi                 start_time  \
0            416565000                  354240000  2016-11-18 14:30:00+00:00   
1            412679190                  354240000  2016-12-11 14:50:00+00:00   
2            440863000                  354240000  2017-06-13 12:50:00+00:00   
3            416563000                  354240000  2016-11-15 11:30:00+00:00   
4            441309000                  354240000  2017-05-19 00:40:00+00:00   

                    end_time  mean_latitude  mean_longitude  duration_hr  \
0  2016-11-19 01:50:00+00:00     -17.039085      -79.063725    11.333333   
1  2016-12-11 19:50:00+00:00     -20.269608      -79.244953     5.000000   
2  2017-06-15 01:20:00+00:00     -62.640767      -60.690240    36.500000   
3  2016-11-16 04:00:00+00:00     -17.046586      -79.061923    16.500000   
4  2017-05-19 20:50:00+00:00     -46.627878      -60.554922    20.166667   

   median_distance_km  median_speed_knots  \
0            0.038188            0.585402   
1            0.020033            0.575663   
2            0.054992            0.019775   
3            0.036427            1.023917   
4            0.034053            0.544031   

                                 coordinates     country iso_3  
0           (-17.0390854214, -79.0637246039)  Antarctica   ATA  
1   (-20.26960835264285, -79.24495254404286)  Antarctica   ATA  
2  (-62.64076718797922, -60.690240192925565)         NaN   NaN  
3   (-17.046585915013658, -79.0619234553677)  Antarctica   ATA  
4   (-46.62787804705882, -60.55492183696471)         NaN   NaN

In [6]:
# note: the combinations fishing vessel and transhipment can be used for the matrix

In [7]:
#merging the illegal encounters to analyse

fishillegaldf=fishdf.merge(illegaldf, left_on='mmsi', right_on='fishing_vessel_mmsi')

In [8]:
#check dataframe

fishillegaldf.head()

mmsi flag      gear_type     length    tonnage  engine_power  \
0  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
1  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
2  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
3  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
4  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   

   country_x  IUU Fishing  fishing_vessel_mmsi  transshipment_vessel_mmsi  \
0  Australia         1.91            503584700                  352241000   
1  Australia         1.91            503584700                  576419000   
2  Australia         1.91            503584700                  576107000   
3  Australia         1.91            503584700                  576107000   
4  Australia         1.91            503584700                  576107000   

                  start_time                   end_time  mean_latitude  \
0  2015-07-04 23:50:00+00:00  2015-07-05 02:00:00+00:00     -34.691229   
1  2013-08-10 03:20:00+00:00  2013-08-10 05:20:00+00:00     -34.690805   
2  2014-07-12 01:10:00+00:00  2014-07-12 03:10:00+00:00     -34.692003   
3  2014-07-19 04:40:00+00:00  2014-07-19 08:30:00+00:00     -34.695524   
4  2014-07-13 23:50:00+00:00  2014-07-15 02:10:00+00:00     -34.695280   

   mean_longitude  duration_hr  median_distance_km  median_speed_knots  \
0      136.085965     2.166667            0.069157            0.031628   
1      136.085175     2.000000            0.027717            0.024307   
2      136.099495     2.000000            0.041409            0.018666   
3      136.094849     3.833333            0.044934            0.029034   
4      136.099197    26.333333            0.039192            0.016855   

                                 coordinates country_y iso_3  
0       (-34.6912286908, 136.08596549450002)       NaN   NaN  
1           (-34.6908052868, 136.0851747694)       NaN   NaN  
2          (-34.69200326485, 136.0994946767)       NaN   NaN  
3  (-34.695523965300005, 136.09484891575002)       NaN   NaN  
4  (-34.695280009899996, 136.09919684837502)       NaN   NaN

In [9]:
#add a new columns for unique if: combination vessel mmsi and transshipment mmsi

fishillegaldf['id_encounter'] = fishillegaldf.index

In [10]:
#check

fishillegaldf.head()

mmsi flag      gear_type     length    tonnage  engine_power  \
0  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
1  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
2  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
3  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   
4  503584700  AUS  other_fishing  23.009784  78.895456    394.867663   

   country_x  IUU Fishing  fishing_vessel_mmsi  transshipment_vessel_mmsi  \
0  Australia         1.91            503584700                  352241000   
1  Australia         1.91            503584700                  576419000   
2  Australia         1.91            503584700                  576107000   
3  Australia         1.91            503584700                  576107000   
4  Australia         1.91            503584700                  576107000   

   ...                   end_time mean_latitude  mean_longitude  duration_hr  \
0  ...  2015-07-05 02:00:00+00:00    -34.691229      136.085965     2.166667   
1  ...  2013-08-10 05:20:00+00:00    -34.690805      136.085175     2.000000   
2  ...  2014-07-12 03:10:00+00:00    -34.692003      136.099495     2.000000   
3  ...  2014-07-19 08:30:00+00:00    -34.695524      136.094849     3.833333   
4  ...  2014-07-15 02:10:00+00:00    -34.695280      136.099197    26.333333   

   median_distance_km  median_speed_knots  \
0            0.069157            0.031628   
1            0.027717            0.024307   
2            0.041409            0.018666   
3            0.044934            0.029034   
4            0.039192            0.016855   

                                 coordinates country_y iso_3 id_encounter  
0       (-34.6912286908, 136.08596549450002)       NaN   NaN            0  
1           (-34.6908052868, 136.0851747694)       NaN   NaN            1  
2          (-34.69200326485, 136.0994946767)       NaN   NaN            2  
3  (-34.695523965300005, 136.09484891575002)       NaN   NaN            3  
4  (-34.695280009899996, 136.09919684837502)       NaN   NaN            4  

[5 rows x 21 columns]

In [11]:
#check columns

fishillegaldf.columns

Index(['mmsi', 'flag', 'gear_type', 'length', 'tonnage', 'engine_power',
       'country_x', 'IUU Fishing', 'fishing_vessel_mmsi',
       'transshipment_vessel_mmsi', 'start_time', 'end_time', 'mean_latitude',
       'mean_longitude', 'duration_hr', 'median_distance_km',
       'median_speed_knots', 'coordinates', 'country_y', 'iso_3',
       'id_encounter'],
      dtype='object')

In [12]:
#check index

fishillegaldf.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            10520, 10521, 10522, 10523, 10524, 10525, 10526, 10527, 10528,
            10529],
           dtype='int64', length=10530)

In [13]:
#columns to drop

columns_drop=['mmsi', 'flag', 'gear_type', 'length', 'tonnage', 'engine_power','fishing_vessel_mmsi','transshipment_vessel_mmsi', 'start_time', 'end_time', 'mean_latitude','mean_longitude', 'duration_hr', 'median_distance_km','median_speed_knots', 'coordinates', 'country_y', 'iso_3']

In [14]:
#dropping columns

fishillegaldf=fishillegaldf.drop(columns_drop, axis=1)

In [15]:
#check

fishillegaldf.head()

country_x  IUU Fishing  id_encounter
0  Australia         1.91             0
1  Australia         1.91             1
2  Australia         1.91             2
3  Australia         1.91             3
4  Australia         1.91             4

In [16]:
#renaming columns

fishillegaldf=fishillegaldf.rename(columns={'country_x':'country'})

In [17]:
#checking the number of occurrences by country

nr_occurrences=(fishillegaldf.groupby('country').agg({'country':'count'})
                     .rename(columns={'country':"nr_occurrences"})
                     .reset_index())

In [18]:
#check

nr_occurrences.head()

country  nr_occurrences
0  Australia               5
1     Belize               4
2   Cambodia              25
3     Canada             183
4      Chile              11

In [19]:
#checking the destribuition of data

nr_occurrences.describe()

nr_occurrences
count       37.000000
mean       284.594595
std        844.214015
min          1.000000
25%          2.000000
50%         11.000000
75%         37.000000
max       4760.000000

In [20]:
#preparing a dataframe for the matrix

totaldf = fishillegaldf.merge(nr_occurrences, how="left", on="country")

In [21]:
#giving labels to the country in order to use it for the matrix

labels, levels = pd.factorize(totaldf['country'])

In [22]:
#check the labels

labels

array([ 0,  0,  0, ..., 36, 36, 36], dtype=int64)

In [23]:
#create new column with the country labels

totaldf['country_id']=labels

In [24]:
#check if correct

totaldf

country  IUU Fishing  id_encounter  nr_occurrences  country_id
0      Australia         1.91             0               5           0
1      Australia         1.91             1               5           0
2      Australia         1.91             2               5           0
3      Australia         1.91             3               5           0
4      Australia         1.91             4               5           0
...          ...          ...           ...             ...         ...
10525    Vanuatu         2.55         10525             133          36
10526    Vanuatu         2.55         10526             133          36
10527    Vanuatu         2.55         10527             133          36
10528    Vanuatu         2.55         10528             133          36
10529    Vanuatu         2.55         10529             133          36

[10530 rows x 5 columns]

### 2 Machine Learning preparation

In [25]:
#looking at the data, decided some countries had very little amount of occurences to be considered into the model

totaldf2 = totaldf[totaldf["nr_occurrences"] >= 7].copy()

In [26]:
#prepare pivot table

features = totaldf2.pivot_table(index="country_id",
                    columns="id_encounter",
                    values="IUU Fishing")

In [27]:
#check pivot table

features

id_encounter  9      10     11     12     13     14     15     16     17     \
country_id                                                                    
2              1.97   1.97   1.97   1.97   1.97   1.97   1.97   1.97   1.97   
3               NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
4               NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
7               NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
10              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
15              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
16              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
17              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
18              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
20              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
21              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
22              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
24              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
26              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
28              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
30              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
31              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
33              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
35              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
36              NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

id_encounter  18     ...  10520  10521  10522  10523  10524  10525  10526  \
country_id           ...                                                    
2              1.97  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
3               NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
4               NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
7               NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
10              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
15              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
16              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
17              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
18              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
20              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
21              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
22              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
24              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
26              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
28              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
30              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
31              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
33              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
35              NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
36              NaN  ...   2.55   2.55   2.55   2.55   2.55   2.55   2.55   

id_encounter  10527  10528  10529  
country_id                         
2               NaN    NaN    NaN  
3               NaN    NaN    NaN  
4               NaN    NaN    NaN  
7               NaN    NaN    NaN  
10              NaN    NaN    NaN  
15              NaN    NaN    NaN  
16              NaN    NaN    NaN  
17              NaN    NaN    NaN  
18              NaN    NaN    NaN  
20              NaN    NaN    NaN  
21              NaN    NaN    NaN  
22              NaN    NaN    NaN  
24              NaN    NaN    NaN  
26              NaN    NaN

In [28]:
#fill nulls with zero to model the matrix

features=features.fillna(0)

In [29]:
#confirm

features.head()

id_encounter  9      10     11     12     13     14     15     16     17     \
country_id                                                                    
2              1.97   1.97   1.97   1.97   1.97   1.97   1.97   1.97   1.97   
3              0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
4              0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
7              0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
10             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   

id_encounter  18     ...  10520  10521  10522  10523  10524  10525  10526  \
country_id           ...                                                    
2              1.97  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3              0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4              0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
7              0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
10             0.00  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

id_encounter  10527  10528  10529  
country_id                         
2               0.0    0.0    0.0  
3               0.0    0.0    0.0  
4               0.0    0.0    0.0  
7               0.0    0.0    0.0  
10              0.0    0.0    0.0  

[5 rows x 10489 columns]

In [30]:
#import more libraries

import matplotlib.pyplot as plt
import seaborn as sns
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

%matplotlib inline

In [31]:

country_features = csr_matrix(features)

In [32]:
#train the model

In [33]:
# note: tried euclidean but cosine seemed more accurate

In [34]:
model_knn = NearestNeighbors(metric="cosine",
                             algorithm="brute",
                             n_jobs=-1)
model_knn.fit(country_features)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1)

In [35]:
#check matrix

country_features

<20x10489 sparse matrix of type '<class 'numpy.float64'>'
	with 10489 stored elements in Compressed Sparse Row format>

In [36]:
#understanding features set up

features.head(20)

id_encounter  9      10     11     12     13     14     15     16     17     \
country_id                                                                    
2              1.97   1.97   1.97   1.97   1.97   1.97   1.97   1.97   1.97   
3              0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
4              0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
7              0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
10             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
15             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
16             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
17             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
18             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
20             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
21             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
22             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
24             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
26             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
28             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
30             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
31             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
33             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
35             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
36             0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00   

id_encounter  18     ...  10520  10521  10522  10523  10524  10525  10526  \
country_id           ...                                                    
2              1.97  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
3              0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
4              0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
7              0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
10             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
15             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
16             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
17             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
18             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
20             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
21             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
22             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
24             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
26             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
28             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
30             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
31             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
33             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
35             0.00  ...   0.00   0.00   0.00   0.00   0.00   0.00   0.00   
36             0.00  ...   2.55   2.55   2.55   2.55   2.55   2.55   2.55   

id_encounter  10527  10528  10529  
country_id                         
2              0.00   0.00   0.00  
3              0.00   0.00   0.00  
4              0.00   0.00   0.00  
7              0.00   0.00   0.00  
10             0.00   0.00   0.00  
15             0.00   0.00   0.00  
16             0.00   0.00   0.00  
17             0.00   0.00   0.00  
18             0.00   0.00   0.00  
20             0.00   0.00   0.00  
21             0.00   0.00   0.00  
22             0.00   0.00   0.00  
24             0.00   0.00   0.00  
26             0.00   0.00

In [37]:
#understanding datafram set up

totaldf2.groupby('country').agg({'country':'count'})

country
country                           
Cambodia                        25
Canada                         183
Chile                           11
China                         1715
Comoros                         64
Fiji                            14
Iceland                         37
Japan                          588
Kiribati                        21
Korea, Republic of             803
Latvia                          20
Lithuania                       35
Norway                          26
Papua New Guinea                17
Peru                            11
Russian Federation            4760
Seychelles                      27
Taiwan, Province of China      950
United States                 1049
Vanuatu                        133

In [38]:
#check how the index is working

features.loc[2].values.reshape(1, -1)

array([[1.97, 1.97, 1.97, ..., 0.  , 0.  , 0.  ]])

In [39]:
#1st cosine
#2nd index of the country similar
#note: second array based on the row position

model_knn.kneighbors(features.loc[2].values.reshape(1, -1), n_neighbors=5)

(array([[0., 1., 1., 1., 1.]]), array([[ 0, 16, 13, 14, 11]], dtype=int64))

In [40]:
#set up to check other countries

def country_choice(country):
    return model_knn.kneighbors(features.loc[country].values.reshape(1, -1), n_neighbors=5)

In [41]:
#call the country wished
#the inserted number is the country_id, not the index according to the outcome

country_choice(4)

(array([[3.05311332e-14, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
         1.00000000e+00]]),
 array([[ 2, 13, 15, 17, 14]], dtype=int64))

In [42]:
#confirming it

features.loc[4]

id_encounter
9        0.0
10       0.0
11       0.0
12       0.0
13       0.0
        ... 
10525    0.0
10526    0.0
10527    0.0
10528    0.0
10529    0.0
Name: 4, Length: 10489, dtype: float64

In [43]:
#understanding the country_id set up

totaldf.groupby(["country", "country_id"]).count()

IUU Fishing  id_encounter  \
country                         country_id                              
Australia                       0                     5             5   
Belize                          1                     4             4   
Cambodia                        17                   25            25   
Canada                          2                   183           183   
Chile                           3                    11            11   
China                           4                  1715          1715   
Colombia                        6                     2             2   
Comoros                         7                    64            64   
Côte d'Ivoire                   5                     1             1   
Fiji                            10                   14            14   
Germany                         8                     1             1   
Iceland                         15                   37            37   
India                           13                    1             1   
Iran, Islamic Republic of       14                    1             1   
Japan                           16                  588           588   
Kiribati                        18                   21            21   
Korea, Republic of              20                  803           803   
Latvia                          22                   20            20   
Lithuania                       21                   35            35   
Micronesia, Federated States of 11                    1             1   
Netherlands                     23                    3             3   
Norway                          24                   26            26   
Oman                            25                    1             1   
Papua New Guinea                28                   17            17   
Peru                            26                   11            11   
Philippines                     27                    4             4   
Poland                          29                    1             1   
Russian Federation              30                 4760          4760   
Saint Kitts and Nevis           19                    1             1   
Seychelles                      31                   27            27   
Spain                           9                     4             4   
Taiwan, Province of China       33                  950           950   
Thailand                        32                    2             2   
Ukraine                         34                    5             5   
United Kingdom                  12                    4             4   
United States                   35                 1049          1049   
Vanuatu                         36                  133           133   

                                            nr_occurrences  
country                         country_id                  
Australia                       0                        5  
Belize                          1                        4  
Cambodia                        17                      25  
Canada                          2                      183  
Chile                           3                       11  
China                           4                     1715  
Colombia                        6                        2  
Comoros                         7                       64  
Côte d'Ivoire                   5                        1  
Fiji                            10                      14  
Germany                         8                        1  
Iceland                         15                      37  
India                           13                       1  
Iran, Islamic Republic of       14                       1  
Japan                           16                     588  
Kiribati                        18                      21  
Korea, Republic of              20                     803  
Latvia                          22   

### 3 Machine learning model user friendly

In [44]:
#creating a data frame to take the right country_id and match with the index

newc_list=totaldf2.groupby('country', as_index=False).agg({'country_id':'mean'}).sort_values(by='country_id', ascending=True)
newc_list

country  country_id
1                      Canada           2
2                       Chile           3
3                       China           4
4                     Comoros           7
5                        Fiji          10
6                     Iceland          15
7                       Japan          16
0                    Cambodia          17
8                    Kiribati          18
9          Korea, Republic of          20
11                  Lithuania          21
10                     Latvia          22
12                     Norway          24
14                       Peru          26
13           Papua New Guinea          28
15         Russian Federation          30
16                 Seychelles          31
17  Taiwan, Province of China          33
18              United States          35
19                    Vanuatu          36

In [45]:
# taking the indeces

distances, indeces = model_knn.kneighbors(features.loc[4].values.reshape(1, -1), n_neighbors=5)




In [46]:
#confirming indeces

indeces

array([[ 2, 13, 15, 17, 14]], dtype=int64)

In [47]:
#check df

totaldf2.head()

country  IUU Fishing  id_encounter  nr_occurrences  country_id
9   Canada         1.97             9             183           2
10  Canada         1.97            10             183           2
11  Canada         1.97            11             183           2
12  Canada         1.97            12             183           2
13  Canada         1.97            13             183           2

In [48]:
j = 0
for i in indeces.flatten():
    country = newc_list.iloc[i, 0]
    if j == 0:
        print("BLACKLIST")
        print(f"Countries with similar behaviour to {country}")
        print("\n")
    else:
        print(f"{j}: {country}")
    j += 1

BLACKLIST
Countries with similar behaviour to China


1: Peru
2: Russian Federation
3: Taiwan, Province of China
4: Papua New Guinea
